### ISSUE TITLE
Docker Fatal error error=Could not secure config

### ISSUE THREAD

**Issue by SvenPausH** [warp-tech/warpgate#1018]
My docker-compose.yaml

version: '3'
services:
  warpgate:
    image: ghcr.io/warp-tech/warpgate
    ports:
      - 2222:2222
      - 8889:8888
      - 33306:33306
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true

docker-compose up

Recreating warpgate_warpgate_1 ... done
Attaching to warpgate_warpgate_1
warpgate_1  | 08:29:42  INFO Warpgate version=0.10.0
warpgate_1  | 08:29:42 ERROR Fatal error error=Could not secure config
warpgate_1  |
warpgate_1  | Caused by:
warpgate_1  |     No such file or directory (os error 2)
warpgate_warpgate_1 exited with code 1

**Comment by Eugeny** [comment]
Have you created a config file first? (manually or through `warpgate setup`)

**Comment by SvenPausH** [comment]
No, I overlooked that.
After I created the config it works.

Thanks
