### ISSUE TITLE
Private key ECC secp384r1 for https

### ISSUE THREAD

**Issue by sanjesss** [warp-tech/warpgate#1077]
Hi!
I trying use warpgate in production environment.
I have my own certificate authority where the keys are issued using the secp384r1 algorithm. The final certificates have the same algorithm. When I try to install the secp384r1 key for https warpgate, I get an error:

ERROR warpgate::commands::run: Server error error error=reading TLS certificate from '/etc/warpgate/tls.crt.pem'
Caused by:
no private keys found in key file

When using the RSA2048 key, everything ran fine. Where can I get comprehensive information about supported algorithms?

**Comment by Eugeny** [comment]
Could this be caused by https://github.com/rustls/rustls/issues/767 (the PEM header). If you can confirm that's the case, I can auto-rewrite the headers
