### ISSUE TITLE
Authelia SSO broke with v0.11.0

### ISSUE THREAD

**Issue by tcheronneau** [warp-tech/warpgate#1105]
I'm using SSO only for HTTP access. 
I've setup it for a while and had no issue so far. I was on the latest image of warpgate and discovered today that it was not working anymore. 
I tried to debug but I see absolutely no logs (neither in warpgate or authelia). So after trying pretty much everything (including starting from scratch). I checked the version and pinned my container to use v0.10.2 to test. 
After that everything works again. 
I cannot say why because again no logs so sorry about that. 
But I can try few stuff if required.

**Comment by Eugeny** [comment]
This is likely already fixed in the nightly build - could you give it a try? And it if doesn't help, run Warpgate with --debug for verbose logs

**Comment by tcheronneau** [comment]
Indeed using the main image is working. Thanks !
