### ISSUE TITLE
I only selected sso login, and after configuration, the login failed. How can I cancel sso login and enable password login?

### ISSUE THREAD

**Issue by 534002646** [warp-tech/warpgate#1112]
I only selected sso login, and after configuration, the login failed. How can I cancel sso login and enable password login?

**Comment by 534002646** [comment]
help me😭

**Comment by Eugeny** [comment]
If you don't have another admin user, you can run `warpgate recover-access`

**Comment by 534002646** [comment]
> If you don't have another admin user, you can run `warpgate recover-access`

![image](https://github.com/user-attachments/assets/b7311f5b-2bd1-4e00-ad24-dcbb42a58015)
An error will occur after execution

**Comment by Eugeny** [comment]
You need to run it in the same environment that you run the actual service in, so that it can access the config file
