### ISSUE TITLE
Authorization error

### ISSUE THREAD

**Issue by 534002646** [warp-tech/warpgate#1147]
![image](https://github.com/user-attachments/assets/82e5c38c-bd00-4cce-ba5f-841eb24ad5a7)
Docker has been updated to the latest main branch version, and login is successful, but operations cannot be performed due to permission errors

**Comment by 534002646** [comment]
@Eugeny Is it a bug, or is it my problem?

**Comment by 534002646** [comment]
![image](https://github.com/user-attachments/assets/1c72fc8b-f490-4043-ad41-021af478a4f5)

**Comment by Eugeny** [comment]
It's a bit hard to judge based on just this - but does your user have the admin role? Does "Manage Warpgate" show up on the homepage at `/` or are you accessing `/@warpgate/admin` directly?

**Comment by 534002646** [comment]
> It's a bit hard to judge based on just this - but does your user have the admin role? Does "Manage Warpgate" show up on the homepage at `/` or are you accessing `/@warpgate/admin` directly?


It's an admin account. Docker pulls the latest trunk like this. Can we modify the SQLite DB to fix it?

**Comment by 534002646** [comment]
> 仅凭这一点来判断有点困难 - 但您的用户是否具有管理员角色？ “管理 Warpgate”是否显示在`/`主页上，或者您是否直接访问`/@warpgate/admin` ？

![image](https://github.com/user-attachments/assets/c85ce738-4170-4b36-be9c-f9523eac6487)
I want to revert to the previous version, but it's showing a new error

**Comment by Eugeny** [comment]
You can't downgrade Warpgate due to DB schema changes.
You can also check the SQLite DB to see if your user still has the admin role assignment in it (`user_roles` table, connecting `users` and `roles`)

**Comment by budachst** [comment]
I had that with the nightly from Monday…. I tried the latest nightly yesterday and that resolved this issue for me.

**Comment by 534002646** [comment]
> You can't downgrade Warpgate due to DB schema changes. You can also check the SQLite DB to see if your user still has the admin role assignment in it (`user_roles` table, connecting `users` and `roles`)

The user_roles table has no issues，I'm not sure why, but I reinitialized the database and restored it after importing the backup data
