### ISSUE TITLE
Connecting Warpgate to AWS RDS PostgreSQL in Private Subnet

### ISSUE THREAD

**Issue by vjmax** [warp-tech/warpgate#1157]
Hi ,

We have an AWS RDS PostgreSQL database located in a private subnet. Is it possible to set up a connection to this RDS instance using Warpgate? If so, could you guide us on how to configure it?

**Comment by Eugeny** [comment]
This should just work - as long as the VM that Warpgate is running on has direct access to the RDS endpoint.
