### ISSUE TITLE
Add possibility to generate ssh keys in the frontend

### ISSUE THREAD

**Issue by moalshak** [warp-tech/warpgate#1178]
When the user clicks on "Add new key", it would be great if they could simply generate one there, instead of always relying on them making an ssh key. The ssh key should be made in the frontend and not the backend of course.

Then they are prompted to download the pair and the public field is automatically filled in.

**Comment by Eugeny** [comment]
This is a weird case because usually people already have their keys, and if they don't, their SSH client almost always has a key generator that's easier to use than downloading a key from the internet.
