### ISSUE TITLE
Clarifications on external_port usage and storing session recordings in S3

### ISSUE THREAD

**Issue by vjmax** [warp-tech/warpgate#1184]
**external_port:** What is the purpose of the external_port parameter in the Warpgate configuration file?  when would it need to be modified?

**Session Recordings in S3**: Is it possible to store Warpgate session recordings in an Amazon S3 bucket?
Is there a built-in feature in Warpgate to directly upload session recordings to S3?

**Comment by Eugeny** [comment]
`external_port` is used to construct connection URLs and settings that are shown to users on the UI - you'll need it if you map Warpgate ports to different port numbers on the NAT

Session recordings can only be stored on the filesystem

**Comment by vjmax** [comment]
When Using Warpgate for long periods consumes significant disk space due to session recordings. While recordings are currently stored on the filesystem, disk space becomes a concern for long-term usage.

Question:
Is it possible to implement session recording compression in Warpgate?

If not currently available, could this feature be considered for future versions?

This would greatly help optimize storage without losing valuable session data.

Thanks.

**Comment by Eugeny** [comment]
I've opened #1205 for this - but just in case you didn't know (it's not obvious), session recordings are also affected by the `logs.retention` config option - old sessions can be rotated away together with their recordings
