### ISSUE TITLE
IPv6 not accessible

### ISSUE THREAD

**Issue by cruse123** [warp-tech/warpgate#1189]
In my environment where public IPv4 is not available, the SSH service has to be exposed via IPv6. However the ssh server refuses the connections via IPv6.

Are there any plans on adding IPv6 support?

Thanks!

Reproducing the issue:
Server side:
```
$ docker run --rm --name warpgate -p 8888:8888 -p 2222:2222 ... (same as in Wiki)
$ docker exec -it warpgate bash
# apt-get update -y && apt-get install iproute2
# ss -tunlp
```
The output indicates the SSH daemon is only listening on IPv4 `0.0.0.0` instead of IPv6 `[::]`
```
tcp              LISTEN            0                 1024                               0.0.0.0:2222                             0.0.0.0:*                users:(("warpgate",pid=1,fd=16))
tcp              LISTEN            0                 1024                               0.0.0.0:8888                             0.0.0.0:*                users:(("warpgate",pid=1,fd=18))
```

Client side:
```
$ ssh "user:machine@<server_ipv4_addr>" -p 2222
# Success!

$ ssh "user:machine@<server_ipv6_addr>" -p 2222
# Connection closed by <server_ipv6_addr> port 2222
```

**Comment by Eugeny** [comment]
Replacing `0.0.0.0` with `[::]` in the listen endpoints in the config file should do the trick:

```
....
ssh:
  listen: '[::]:2222'
```

**Comment by 534002646** [comment]
> Replacing `0.0.0.0` with `[::]` in the listen endpoints in the config file should do the trick:
> 
> ```
> ....
> ssh:
>   listen: '[::]:2222'
> ```

It seems that [::] is correctly set as the listening address, but it is still inaccessible.
