### ISSUE TITLE
is warpgate encrypted end-to-end ?

### ISSUE THREAD

**Issue by lfundaro** [warp-tech/warpgate#152]
Hi 👋 . Cool project ! I have a question that I'm unable to answer because I'm illiterate on Rust 🙈 . 

I noticed I need to drop warpgate's ssh public keys in the `authorized_host` of the end host. Does this mean, warpgate makes two ssh sessions ? one between client and warpgate and another between warpgate and end host ?

thanks !

**Comment by Eugeny** [comment]
Thanks! Wargate connections are encrypted, but not _end-to-end_. SSH connection terminates at Warpgate itself, which can observe the traffic (and records it for auditing!).

WG will set up its own connection to the target host, authenticate, and then connect the user and the target together similarly to an old school telephone exchange, while managing both connections.

**Comment by lfundaro** [comment]
thank you ! 🙇
