### ISSUE TITLE
Session recording is just black

### ISSUE THREAD

**Issue by apiening** [warp-tech/warpgate#18]
When I select a recorded session I get an entry `shell-channel-2` under `Recordings`. When I click on the entry, I get a screen with the headline `Session recording` and a video-player.
Clicking on the play button in the center of the player starts the Playback and the playback progress indicator at the bottom is updated, but the player screen is just plain black.

On the browser console I get:
```
containerW = 0 [index.js:3025:12](https://172.16.152.3:8888/node_modules/asciinema-player/dist/index.js)
player mounted [index.js:2863:20](https://172.16.152.3:8888/node_modules/asciinema-player/dist/index.js)
containerW = 1296 [index.js:3025:12](https://172.16.152.3:8888/node_modules/asciinema-player/dist/index.js)
batched 259 frames to 87 frames [index.js:3839:16](https://172.16.152.3:8888/node_modules/asciinema-player/dist/index.js)
containerW = 1296 [index.js:3025:12](https://172.16.152.3:8888/node_modules/asciinema-player/dist/index.js)
```
and when I interact with the player (clicking on pause / play) I get an exception: `Uncought RuntimeError: unreachable executed`.

**Comment by Eugeny** [comment]
Thanks for testing! Could you please send the recording file (from /var/lib/warpgate/recordings) to me at x@null.page?

**Comment by apiening** [comment]
Sure, I just did.

**Comment by Eugeny** [comment]
Figured it out - for some reason, the client has never sent the PTY size information and now the player can't display the terminal.
