### ISSUE TITLE
AES-CTR support (cipher issue with shellfish/blink on iPad)

### ISSUE THREAD

**Issue by rolikeusch** [warp-tech/warpgate#186]
I'm not sure who can fix this issue, so I start here ;)

I'm a heavy iPad user, but none of the used ssh client is able to connect to warpgate :( when I connect with [ShellFish](https://secureshellfish.app) I see the following message in shellfish:
`Error: Connection test failed: Error Domain=SSH Code=-5 "Unable to establish SSH connection: Encryption key exchange failed." UserInfo={NSLocalizedDescription=Unable to establish SSH connection: Encryption key exchange failed.}`
and in warpgate is see this:
`Could not find common cipher, other side only supports Ok("aes128-ctr,aes192-ctr,aes256-ctr,aes256-cbc,rijndael-cbc@lysator.liu.se,aes192-cbc,aes128-cbc,blowfish-cbc,arcfour128,arcfour,cast128-c
bc,3des-cbc"), we only support [Name("chacha20-poly1305@openssh.com"), Name("aes256-gcm@openssh.com")] `

also when I use the [blink](https://blink.sh) ssh client I see:
`Error connecting to warp. connError(msg: "kex error : no match for method mac algo client->server: server [none], client [hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1]")`

I looks like those clients use different cipher then warpgate support.

**Comment by Eugeny** [comment]
All new kex/cipher/hmac algorithms (including AES-CTR variations) from [warp-tech/russh](https://github.com/warp-tech/russh) are now available in the nightly build (once it's ready): https://github.com/warp-tech/warpgate/actions/runs/2800292494
