### ISSUE TITLE
Command Error in Wiki

### ISSUE THREAD

**Issue by ngjames** [warp-tech/warpgate#193]
To be specific, in the page [User authentication and roles](https://github.com/warp-tech/warpgate/wiki/User-authentication-and-roles). 

The line: (it can also run in unattended mode: `echo 123 | warpgate hash`)
should be `echo -n 123 | warpgate hash` since echo will create a new line. Causing the hash to be mismatched.

**Comment by Eugeny** [comment]
Fixed, thanks!
