### ISSUE TITLE
allow self signed certificates in http targets

### ISSUE THREAD

**Issue by rolikeusch** [warp-tech/warpgate#206]
is it possible to add an option to ignore  certificates error? i use a few internal services with a self signed certificate and if i use those as a http target, warpgate crash and have [this](https://github.com/warp-tech/warpgate/issues/205) issue.

**Comment by Eugeny** [comment]
You can now allow self-signed certificates in the nightly build as described here: https://github.com/warp-tech/warpgate/wiki/Target-TLS-options (by setting `http.tls.verify` to `false` on the target config.
