### ISSUE TITLE
Wish: Describe a running warpgate

### ISSUE THREAD

**Issue by stappersg** [warp-tech/warpgate#22]
Hi,

Here a person that has heared about teleport (but never used it (due the "high corporate appearance")).

I, seasoned sysadmin, miss a description how _warpgate_ looks like when it is running.

This are the things that I made up myself:

* `warpgate` listens by default on port 2222 and can be configured to listen on the default ssh port ( port 22)
* Configuration lives in a _sql database_,  configuration can be live updated
* There is a _CLI user interface_ and a _webbased UI_, both use the same _REST API_ that listens at configurable port
* Session recordings are stored as files.  Recording sessions is optional

**Comment by stappersg** [comment]
Reading https://github.com/warp-tech/warpgate/wiki/Getting-started did inform me about `--config /etc/warpgate.yaml` and web (web only?) user interface.

Where and how the (optional) session recordings are stored is still unclear.


I hope that the toplevel README gets the _what I missed_ information.

**Comment by Eugeny** [comment]
Thanks for the feedback! I've updated the README. Re session recordings: if enabled, they're stored in the data directory / `recordings` (default: `/var/lib/warpgate/recordings`), but aren't meant to be accessed directly. You can view/download them from the admin UI.
