### ISSUE TITLE
Feature Request: Support for other KEX algorithm

### ISSUE THREAD

**Issue by Netfreak25** [warp-tech/warpgate#232]
First of all: Thanks for this nice peace of Software!

We have multiple Aruba Switches in our Infrastructure and I was trying to add them to Warpgate but I wasn't succesfull.
There is an issue with the key exchange algorithm. The one offered by the Aruba Switch is not supported by Warpgate and vice versa.

As with other Linux hosts I tried to add the warpgate kex algorithm to the Aruba Switch, but it looks like it does not support it.

Would it be possible to add additional kex algorithms to warpgate?

ssh admin:"Switch Aruba"@warpgate -p 2222
admin:Switch Aruba@warpgate's password:
channel 0: protocol error: close rcvd twice
 Warpgate  Selected target: Switch Aruba
 Connection failed  No common key exchange algorithm
Connection to warpgate closed.

02.08.2022 11:26:31 DEBUG russh::negotiation: Could not find common kex algorithm, other side only supports Ok("diffie-hellman-group14-sha1"), we only support [Name("curve25519-sha256@libssh.org")]

**Comment by Eugeny** [comment]
All new kex/cipher/hmac algorithms (including classic DH key exchanges) from [warp-tech/russh](https://github.com/warp-tech/russh) are now available in the nightly build (once it's ready): https://github.com/warp-tech/warpgate/actions/runs/2800292494
