### ISSUE TITLE
Support for SFTP?

### ISSUE THREAD

**Issue by Jojuh** [warp-tech/warpgate#246]
SCP seems to work fine, but should SFTP via warpgate be supported also?

If I try with `sftp -o User=<username:target> <warpgate-address>`, I am prompted with the user:target (and even OTP correctly), but the connection is never established fully and will eventually timeout. If I try with scp or even WinSCP set to Protocol: SCP, file transfers work fine.

The warpgate logs only show: `Requesting subsystem sftp channel=<channel id>` Debug log only shows additional `Data channel=2 data=<somebinary> session=<session id> session_username=<username>`

RHEL9 are moving from scp to sftp and WinSCP also defaults to SFTP, so this would be highly relevant to my interests: https://www.redhat.com/en/blog/openssh-scp-deprecation-rhel-9-what-you-need-know

**Comment by Eugeny** [comment]
Great find! `scp` seems to request both SFTP and shell channels while `sftp` only requests the SFTP subsystem from the server - and that alone didn't trigger Warpgate to start connecting to the target - now fixed in fbd8d0d.
