### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by rolikeusch** [warp-tech/warpgate#257]
I'm not able to login in to v 0.5.0, well I can login but after a successful login I get endless redirects. if I start warpgate in the foreground I see only this:

`06:30:55  INFO Warpgate version=0.5.0                                                                                                                                                                            
06:30:55  INFO Using config: "/etc/warpgate.yaml" (users: 1, targets: 1, roles: 1)                                                                                                                               
06:30:55  INFO --------------------------------------------                                                                                                                                                      
06:30:55  INFO Warpgate is now running.                                                                                                                                                                          
06:30:55  INFO Accepting SSH connections on 0.0.0.0:2222                                                                                                                                                         
06:30:55  INFO Accepting HTTP connections on https://warpgate:8888                                                                                                                                          
06:30:55  INFO --------------------------------------------                                                                                                                                                      
06:30:55  INFO Listening address=0.0.0.0:2222                                                                                                                                                                    
06:30:55  INFO Listening address=warpgate:8888                                                                                                                                                              
06:31:35  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate status=200 OK                                                                                                                   
06:31:35  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate/assets/gateway.e9b0efd6.js status=200 OK                                                                                        
06:31:35  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate/assets/gateway.55661b15.css status=200 OK                                                                                       
06:31:35  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate/assets/Logo.081db3d4.css status=200 OK                                                                                          
06:31:35  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate/assets/Alert.273812d1.js status=200 OK                                                                                          
06:31:35  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate/assets/Logo.a5b40f23.js status=200 OK                                                                                           
06:31:35  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate/assets/api.af344ead.js status=200 OK                                                                                            
06:31:35  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate/api/info status=200 OK                                                                                                          
06:31:35  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate/api/sso/providers status=200 OK                                                                                                 
06:31:35  WARN HTTP: Request failed method=GET url=https://warpgate:8888/@warpgate/api/auth/state status=404 Not Found                                                                                      
06:31:40  INFO HTTP: Authenticated username=admin                                                                                                                                                                
06:31:40  INFO HTTP: Request method=POST url=https://warpgate:8888/@warpgate/api/auth/login status=201 Created                                                                                              
06:31:40  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate/api/info status=200 OK session=af2d4de4-8d86-40b7-ba58-07076b5e0469 session_username=admin                                      
06:31:41  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate status=200 OK session=af2d4de4-8d86-40b7-ba58-07076b5e0469 session_username=admin                                               
06:31:41  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate/api/info status=200 OK session=af2d4de4-8d86-40b7-ba58-07076b5e0469 session_username=admin                                      
06:31:41  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate/api/auth/state status=200 OK session=af2d4de4-8d86-40b7-ba58-07076b5e0469 session_username=admin                                
06:31:41  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate/api/sso/providers status=200 OK session=af2d4de4-8d86-40b7-ba58-07076b5e0469 session_username=admin                             
06:31:41  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate status=200 OK session=af2d4de4-8d86-40b7-ba58-07076b5e0469 session_username=admin                                               
06:31:41  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate/api/info status=200 OK session=af2d4de4-8d86-40b7-ba58-07076b5e0469 session_username=admin                                      
06:31:41  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate/api/sso/providers status=200 OK session=af2d4de4-8d86-40b7-ba58-07076b5e0469 session_username=admin                             
06:31:41  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate/api/auth/state status=200 OK session=af2d4de4-8d86-40b7-ba58-07076b5e0469 session_username=admin                                
06:31:41  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate status=200 OK session=af2d4de4-8d86-40b7-ba58-07076b5e0469 session_username=admin                                               
06:31:41  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate/api/info status=200 OK session=af2d4de4-8d86-40b7-ba58-07076b5e0469 session_username=admin                                      
06:31:41  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate/api/sso/providers status=200 OK session=af2d4de4-8d86-40b7-ba58-07076b5e0469 session_username=admin                             
06:31:41  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate/api/auth/state status=200 OK session=af2d4de4-8d86-40b7-ba58-07076b5e0469 session_username=admin                                
06:31:41  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate status=200 OK session=af2d4de4-8d86-40b7-ba58-07076b5e0469 session_username=admin                                               
06:31:41  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate/api/info status=200 OK session=af2d4de4-8d86-40b7-ba58-07076b5e0469 session_username=admin                                      
06:31:41  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate/api/auth/state status=200 OK session=af2d4de4-8d86-40b7-ba58-07076b5e0469 session_username=admin                                
06:31:41  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate/api/sso/providers status=200 OK session=af2d4de4-8d86-40b7-ba58-07076b5e0469 session_username=admin                             
06:31:41  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate status=200 OK session=af2d4de4-8d86-40b7-ba58-07076b5e0469 session_username=admin                                               
06:31:41  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate/api/info status=200 OK session=af2d4de4-8d86-40b7-ba58-07076b5e0469 session_username=admin                                      
06:31:41  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate/api/auth/state status=200 OK session=af2d4de4-8d86-40b7-ba58-07076b5e0469 session_username=admin                                
06:31:41  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate/api/sso/providers status=200 OK session=af2d4de4-8d86-40b7-ba58-07076b5e0469 session_username=admin                             
06:31:41  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate status=200 OK session=af2d4de4-8d86-40b7-ba58-07076b5e0469 session_username=admin                                               
06:31:41  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate/api/info status=200 OK session=af2d4de4-8d86-40b7-ba58-07076b5e0469 session_username=admin                                      
06:31:41  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate/api/auth/state status=200 OK session=af2d4de4-8d86-40b7-ba58-07076b5e0469 session_username=admin                                
06:31:41  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate/api/sso/providers status=200 OK session=af2d4de4-8d86-40b7-ba58-07076b5e0469 session_username=admin                             
06:31:41  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate status=200 OK session=af2d4de4-8d86-40b7-ba58-07076b5e0469 session_username=admin                                               
06:31:41  INFO HTTP: Request method=GET url=https://warpgate:8888/@warpgate/api/info status=200 OK session=af2d4de4-8d86-40b7-ba58-07076b5e0469 session_username=admin`

**Comment by Eugeny** [comment]
* Does clearing the browser cache help?
* What's shown if you open https://warpgate:8888/@warpgate/api/info in the browser?

**Comment by rolikeusch** [comment]
- no this did not help. also used 3 different browser. on my Mac safari and chrome and on a linux client the edge browser
- when I open this link I see:
` {"authorized_via_ticket":false,"external_host":"warpgate","ports":{"http":null,"mysql":null,"ssh":null},"selected_target":null,"username":null,"version":"0.5.0"}`

**Comment by Eugeny** [comment]
Fixed in v0.5.1!
