### ISSUE TITLE
HTTP target through reverse proxy not working.

### ISSUE THREAD

**Issue by filipton** [warp-tech/warpgate#274]
I tried to setup reverse proxy(nginx, haproxy) to warpgate, but it doesn't works.
When im trying to enter any HTTP target site, I can only see 403 error!

It's weird problem, because after logging in and trying to enter any HTTP target when im going to "/" (for eg. https://warpgate.example.com/) Im getting the same 403 error.
The only way I've found to temporarily fix this is to clear cookies.

Logs doesn't seems to help much, but there they are:
![image](https://user-images.githubusercontent.com/37213766/185964145-9fac9e8c-7b67-4e4f-9cfd-cc0a75d2ff6c.png)

**Comment by Eugeny** [comment]
In the browser, are you seeing an error page with Warpgate logo on it (403 from target), or just "Forbidden" as plain text (403 from Warpgate itself)?

**Comment by filipton** [comment]
> In the browser, are you seeing an error page with Warpgate logo on it (403 from target), or just "Forbidden" as plain text (403 from Warpgate itself)?
> 
> P.S. if you need to go back to target selection, you can navigate to `/@warpgate` manually

I'm seeing 403 from target (i'm using cloudflare for dns proxy, but it doesn't work either with plain IP with different port from haproxy).
I managed to fix it, chaning target url to dns without cloudflare proxy enabled, but it's still weird that with cloudflare proxy enabled i can access page only while using "normal port".

Cloudflare proxy with Nginx: 
![image](https://user-images.githubusercontent.com/37213766/185970864-5e8051e3-cb82-48f4-9ee7-3dfee558e76a.png)

Plain IP with different port (haproxy):
![image](https://user-images.githubusercontent.com/37213766/185971334-6428de0b-adcd-49ac-a3b2-75c97d7cf71d.png)

Normal port (working as expected): 
![image](https://user-images.githubusercontent.com/37213766/185972159-ea58b7e4-01fc-4415-bbc0-961426b5d61b.png)

**Comment by Eugeny** [comment]
Unfortunately I don't have any experience working with Cloudflare, but it looks like you might be tipping off some of its protection rules. Here's what I found: https://community.cloudflare.com/t/community-tip-fixing-error-403-forbidden/53308

**Comment by filipton** [comment]
Unfortunately I don't have any experience working with Cloudflare, but it looks like you might be tipping off some of its protection rules. Here's what I found: https://community.cloudflare.com/t/community-tip-fixing-error-403-forbidden/53308

After some tesing i found out possible cause of problem. There is a problem with Host header.

```
Extracted from headers:
"host":"127.0.0.1:8888"
```

So with that, any page going through cloudflare proxy or just page hosted on external service won't work.
Warpgate with reverse proxy set to `test.example.com` will send request to `target.example.com` with `test.example.com` host header not `target.example.com`.
