### ISSUE TITLE
Use Own SSH Keys

### ISSUE THREAD

**Issue by wolveix** [warp-tech/warpgate#282]
Apologies if this is already supported, I can't seem to find any issues or wiki pages referencing it.

Is it possible to replace Warpgate's own SSH keys with your own? And is it possible to have multiple sets of SSH keys? I work for multiple organizations, and have a separate key for each one.

Thanks!

**Comment by Eugeny** [comment]
Yes, you'll find the key files in the folder as set by the `ssh.keys` config option (normally /var/lib/warpgate/ssh-keys). However using separate client keys per target is not supported.

**Comment by kakawait** [comment]
@Eugeny when generated key using `ssh-keygen -t ed25519` and putting replace `client-ed25519` on UI i've following error message

<img width="1361" alt="Screenshot 2024-01-17 at 15 57 01" src="https://github.com/warp-tech/warpgate/assets/275609/d4da0b84-be25-4779-98e8-cb67a0e884b0">
