### ISSUE TITLE
UI/API: Bad credentials in db when saving SSH web auth type with SSO

### ISSUE THREAD

**Issue by notnooblord** [warp-tech/warpgate#346]
Selecting web-based auth (using with sso) in web, results in "sso" being saved to db.
![image](https://user-images.githubusercontent.com/11678665/190532582-8c845be2-c7f3-4aa2-9ef5-7e42b668ae49.png)

Currently saving in UI results in `credential_policy = '{"http":["sso"],"ssh":["sso", "web"]}'`  

But it **should be saved** as `credential_policy = '{"http":["sso"],"ssh":["web"]}'`  

Sso, specified in ssh cred_policy results in auth button returning SsoNeeded state after approve.  
So this configuration after editing in UI can no longer be used :(

**Comment by Eugeny** [comment]
Is this the case for new users as well, or did you have `sso` under `ssh` prior to config->db migration?

**Comment by notnooblord** [comment]
Yes, just checked with brand new user. Settings below produce bug.
<img width="616" alt="image" src="https://user-images.githubusercontent.com/11678665/190828625-85a0f8ad-2faf-4846-8af7-3c89d17a1501.png">

Saved in db as: `|login|[{"email":"xxxx.xxx@xxx.com","provider":"google","type":"sso"}]|{"http":["sso"],"ssh":["sso","web"]}`

Should be: `|login|[{"email":"xxxx.xxx@xxx.com","provider":"google","type":"sso"}]|{"http":["sso"],"ssh":["web"]}`
