### ISSUE TITLE
OneTimeCode is not required every login 

### ISSUE THREAD

**Issue by DunklerPhoenix** [warp-tech/warpgate#352]
Sometimes I can log in without the OTC.
There are no logs available.
Version 0.6.3 - Docker

**Comment by Eugeny** [comment]
Have you set the user's auth policy to require both?

**Comment by DunklerPhoenix** [comment]
Hm it's set for http to any. I expect that warpgate then asks for every added auth method. But the actual behavior is that it always asks for the password for the Webinterface and sometimes additional for the 2fa.

**Comment by Eugeny** [comment]
"any" means "any single one" in this context. If you have it enabled and e.g. input an incorrect password, it'll ask for the other credential type instead. You want to disable "any" and explicitly select both credential types

**Comment by DunklerPhoenix** [comment]
![ezgif-4-ae3fd69e05](https://user-images.githubusercontent.com/1261305/191464765-29925bac-969f-4315-a98b-03ae2d7d7086.gif)
![chrome_OwpIsvxuUU](https://user-images.githubusercontent.com/1261305/191464770-f92fbadf-8589-4ba6-97d0-81b003bd1bea.jpg)


It should ask for 2FA If I understood it correctly, right?

**Comment by DunklerPhoenix** [comment]
Ahhh I'm stupid xD http is set to any. Changed it to OTP+Password now and it works.
