### ISSUE TITLE
Auto-enable 2FA policy when adding OTP to a user

### ISSUE THREAD

**Issue by DunklerPhoenix** [warp-tech/warpgate#353]
Heho.
If I add an OTC the SSH login ask only for the OTC and not the password. Is this behavior intentional?

WG: 0.6.3 Docker

**Comment by Eugeny** [comment]
Yes, this is expected. By default any single credential suffices, and you need to explicitly select the required credentials in the "Auth policy" section like this: 
<img width="684" alt="image" src="https://user-images.githubusercontent.com/161476/191320979-fad8d40b-370c-4ad6-9b5f-76bfd747ad81.png">

But automatically enabling this when adding a password + OTP makes sense so I'll keep this ticket open as an enhancement

**Comment by DunklerPhoenix** [comment]
I tried this auth policy, but it still asks only for 2fa without password. Does warpgate take some time to enable saved settings?

**Comment by Eugeny** [comment]
No, they're applied immediately. Could you please post the full output of an ssh login with ssh -v (verbose output)?

**Comment by DunklerPhoenix** [comment]
Ahhh! The settings are sometimes not saved. There is no confirmation after pressing "update". I need to force reload the page (with clearing cache) to see the actual active settings. So even if my screenshot from above shows OTP+Password, it was still set to any. xD
