### ISSUE TITLE
Connection Instrucions doesn't work in windows

### ISSUE THREAD

**Issue by DunklerPhoenix** [warp-tech/warpgate#358]
Heho
The connection instruction does not work in windows:
Instruction: ssh 'streetcy:alphabit02@server' -p 2222
Windows CMD: ssh: Could not resolve hostname server': Host unknown

If I remove both ' ', it works: ssh streetcy:alphabit02@server -p 2222

**Comment by andreasbrett** [comment]
> If I remove both ' ', it works: ssh streetcy:alphabit02@server -p 2222

Double quotes are the better solution as that also works for targets that have names with spaces.
