### ISSUE TITLE
Warpgate SSH disabled by default

### ISSUE THREAD

**Issue by DunklerPhoenix** [warp-tech/warpgate#359]
Heho
Is it a wanted behavior that the WG SSH server is disabled by default?
I wondered yesterday why I can't connect to the SSH until I realized that the server is disabled by default in the configuration file.

**Comment by Eugeny** [comment]
Is this an existing setup you've upgraded from pre-0.4? [From v0.4 on the default is off for all protocols](https://github.com/warp-tech/warpgate/releases/tag/v0.4.0) and they need to be explicitly enabled. 

For new setups, `warpgate setup` asks whether individual protocols should be enabled and generates the `enable:` config entries.
