### ISSUE TITLE
Update config via API

### ISSUE THREAD

**Issue by Fraccaman** [warp-tech/warpgate#382]
I didn't read anything about this, but it would be nice to be able to manage at least targets and user via API.

**Comment by Eugeny** [comment]
This is possible starting with v0.6. You can find the OpenAPI schemas in https://github.com/warp-tech/warpgate/blob/main/warpgate-web/src/admin/lib/openapi-schema.json (config editing) and https://github.com/warp-tech/warpgate/blob/main/warpgate-web/src/gateway/lib/openapi-schema.json (auth etc)
