### ISSUE TITLE
Using postgres as database

### ISSUE THREAD

**Issue by notnooblord** [warp-tech/warpgate#452]
Currently warpgate uses sqlite which is totally fine, but I have some scaleability concerns.

Since warpgate is using sea-orm it should be fine to replace connection string with postgres?  
Any work to be done here ?

**Comment by stappersg** [comment]
Advice:  Avoid yes-no-questions

**Comment by Eugeny** [comment]
That actually should be as easy as enabling the `sqlx-postgres` feature on the `sea-orm` crate and then using a `postgres://` URL for the `database_url` config option (not tested though!)

**Comment by Eugeny** [comment]
I've now added direct `postgres` and `mysql` features to `warpgate` itself, enabled them by default in the Docker image and added a `--database-url` option to `warpgate unattended-setup`

**Comment by vitaaaaa1** [comment]
> I've now added direct `postgres` and `mysql` features to `warpgate` itself, enabled them by default in the Docker image and added a `--database-url` option to `warpgate unattended-setup`我已经为它添加了直接访问和一些新功能，并将它们默认启用在Docker镜像中，并添加了一个选项。

hello,Could you please confirm if the following URL format for connecting to a PostgreSQL database in the configuration file is correct: `postgres://myuser:mypassword@localhost:5432/mydatabase`
