### ISSUE TITLE
docs: how to authenticate with the api

### ISSUE THREAD

**Issue by ntimo** [warp-tech/warpgate#460]
I am currently trying to use Ansible to create targets in warpgate and  I am struggling hard to get the authorization working. I tried to use basic auth but this does not seem to work. What do I need to do in order to use the API?

**Comment by Eugeny** [comment]
I'm planning to add token authentication, but right now the only way to authenticate is through the normal login flow and use the session cookie - it's a separate API that is documented in https://github.com/warp-tech/warpgate/blob/main/warpgate-web/src/gateway/lib/openapi-schema.json 

The relevant API operations are: `login`, `otpLogin` and `startSSO`

**Comment by ntimo** [comment]
Thank you very much :) @Eugeny

**Comment by stappersg** [comment]
On Mon, Nov 07, 2022 at 09:07:05AM -0800, Timo wrote:
> Thank you very much :) @Eugeny 

Consider to express being grateful by
creating merge requests against the documentation.

**Comment by clysto** [comment]
Is the feature of token authentication on the way?

**Comment by Eugeny** [comment]
Will be tracked in https://github.com/warp-tech/warpgate/issues/1186

**Comment by codyro** [comment]
I wrote a (mildly kludge) Ansible module to handle targets using the current authentication method. 

I'll push it to a repo today in case it's helpful to anyone else until the API functionality/tokens are more developed. I will bump this once I do so.

**Comment by Eugeny** [comment]
The nightly now has UI to creation of API tokens and a Swagger API playground

**Comment by codyro** [comment]
@ntimo 

It's belated, but better late than never! This was tossed together quickly for my own use. (I personally have only used it for adding/removing/modifying `ssh` targets, but it should work.) 

This was made a bit ago before the addition of [API tokens](https://github.com/warp-tech/warpgate/pull/1191), so it authenticates the old-fashioned way.

If anyone uses it, I'll clean it up. It should serve as an okay boilerplate/example.
