### ISSUE TITLE
Credentials dont save in docker

### ISSUE THREAD

**Issue by matt-horwood-mayden** [warp-tech/warpgate#512]
Hello 👋🏼 

I have got this setup in docker, but cant connect over SSH as I cant store either a password or key for any users. Is this a know issue?

watching the logs I can see me select the user, but no log for a password set.

**Comment by Eugeny** [comment]
Just a sanity check - you're clicking "Update" after setting the password, right?

**Comment by matt-horwood-mayden** [comment]
so that would help, Im a muppet. Sorry 🤦🏼
