### ISSUE TITLE
Allow non-admin users to edit their own credentials

### ISSUE THREAD

**Issue by seysn** [warp-tech/warpgate#673]
Hello,

It could be interesting to allow non-admin user to have the ability to edit their own credentials. This way, users wouldn't need to ask an administrator to modify their own informations.

**Comment by D0ublek1ll** [comment]
I second this motion. Managing their own 2FA and changing their own passwords is quite the essential feature for any serious use.

**Comment by andreasbrett** [comment]
Apart from SSO I think all the credentials should be editable by the user itself not by an admin.

**Comment by dillfrescott** [comment]
Yes! I was going to post something along these lines!

**Comment by clysto** [comment]
Is this feature in the plan? @Eugeny

**Comment by khalangy** [comment]
Hello,

Fist thanks for this tool, it's almost the perfect bastion for me :D 

I also think all users should be able to modify their own credential.
Is this feature could be add to the road map @eugeny ?

**Comment by khalangy** [comment]
Thnks a lot ! 
When do you plan to release a version including this feature ?

**Comment by Eugeny** [comment]
Fairly soon - I want to fix a few other things before that. If you can give the nightly build a try and a quick test, that would be appreciated!

**Comment by khalangy** [comment]
Ok I'll try this ! 
Just a comment, the nighntly link in the Getting Started page is wrong, but it's ok on the Readme :)
