### ISSUE TITLE
Azure redirect URI Invalid Character

### ISSUE THREAD

**Issue by rodlord5000** [warp-tech/warpgate#690]
When trying to register the redirect URI in Azure it will not allow me to save, it marks the URI as invalid once there is an @ character in it.

![image](https://user-images.githubusercontent.com/114850211/225217462-24560f94-532f-4f6a-a7ab-202282671373.png)

**Comment by WilliamB78** [comment]
@rodlord5000 a way to add the redirect URI in the portal azure is to add a temporary valid url in the form in your screenshot (something like https://yourwarpgate.domain/warpgate/api/sso/return), then you go to the "Manifest" page and you change the value in the json for "replyUrlsWithType" with the working url (like https://yourwarpgate.domain/@warpgate/api/sso/return)

**Comment by rodlord5000** [comment]
> @rodlord5000 a way to add the redirect URI in the portal azure is to add a temporary valid url in the form in your screenshot (something like https://yourwarpgate.domain/warpgate/api/sso/return), then you go to the "Manifest" page and you change the value in the json for "replyUrlsWithType" with the working url (like https://yourwarpgate.domain/@warpgate/api/sso/return)

This worked, thank you.
