### ISSUE TITLE
Is warpgate affected by GHSA-cqvm-j2r2-hwpg

### ISSUE THREAD

**Issue by ntimo** [warp-tech/warpgate#693]
Hello,
I just saw https://github.com/warp-tech/russh/security/advisories/GHSA-cqvm-j2r2-hwpg and wanted to ask if warpgate is also effected by this russh vuln, since warpgate uses russh. And if so, when you are planning to release a patch.

best wishes,
Timo

**Comment by Eugeny** [comment]
Yes - it's now fixed in v0.7.1
