### ISSUE TITLE
Setup and run with docker-compose

### ISSUE THREAD

**Issue by JPustkuchen** [warp-tech/warpgate#745]
Hi and thank you for this super genius piece of software first! Great work!

This issue is a documentation / feature request / support request to allow installing and running warpgate using a docker-compose.yml
So the expected outcome would be
- a documentation page like (or at): https://github.com/warp-tech/warpgate/wiki/Getting-started-on-Docker but for docker-compose
- a docker-compose.yml template to use
- eventually some alignments to the setup process, if needed

The benefit of using a docker-compose yml are from my perspective the clear definition, simplicity and reproduction of the container setup.

I found this issue where someone was already using a docker-compose.yml for warpgate, I think it was created manually:
https://github.com/warp-tech/warpgate/issues/311

But running `docker-compose up` with that template doesn't work, as the setup command is missing at first start.
See getting started on docker: `docker run --rm -it -v <data dir>:/data ghcr.io/warp-tech/warpgate setup`

I haven't used docker-compose for a while, so I sadly don't remember and couldn't find a clear way, how to run the setup command at first start using docker-compose. 

I tried adding
```
version: "3"
services:
  warpgate:
    [...]
    # SETUP:
    command: setup
    stdin_open: true # docker run -i
    tty: true        # docker run -t    
```
which seems to start the setup at first run, but then stopped, as the step

> Do you want to record user sessions?
isn't shown this way.

So I'd like to hear, if the maintainers or community likes the idea to provide a docker-compose.yml template and eventually change the install process to auto-run setup, if it wasn't run before?

Thanks once again!

**Comment by JPustkuchen** [comment]
Seems like this is already possible with the docker-compose.yml from the mentioned issue.
You just have to run
`docker-compose run warpgate setup` to run the setup! :)

**Comment by zypherion** [comment]
I'd second that a walkthrough or at least an example template for compose would be appreciated. I'm trying to deploy from portainer and hitting some speed bumps.

**Comment by Eugeny** [comment]
The [guide](https://github.com/warp-tech/warpgate/wiki/Getting-started-on-Docker#running-with-docker-compose) has been updated!

**Comment by JPustkuchen** [comment]
Impressive, thank you soooo much @Eugeny!
