### ISSUE TITLE
Missing docker image for v0.7.3

### ISSUE THREAD

**Issue by epou** [warp-tech/warpgate#852]
I've seen that the GitHub action in charge of pushing the new docker images failed when v0.7.3 was released.

See:
- https://github.com/warp-tech/warpgate/actions/runs/5505775857/job/14903556848
- https://github.com/warp-tech/warpgate/actions/runs/5505775638/job/14903556310

It seems that what made fail the build was solved in: https://github.com/warp-tech/warpgate/issues/830

Would you mind running it again?

BTW, not sure if the v.0.7.3 should be moved to commit 1a025dd138aec7c1603b8124f11214c99fe6df5b

**Comment by Eugeny** [comment]
Released v0.7.4 just to keep it clean :)
