### ISSUE TITLE
Accept X-Forwarded-For from a proxy in front of Warpgate

### ISSUE THREAD

**Issue by netwaze** [warp-tech/warpgate#882]
Hello, 
i tried to run warpgate behind haproxy but i still have the ip address of my haproxy in my logs. is there any configuration to do to have the public ip address?
backend haproxy : 

backend http_back_gate
   balance roundrobin
   option httpclose
   cookie JSESSIONID prefix
   option forwardfor
   http-request set-header X-Forwarded-Proto https if { ssl_fc }
   http-request set-header X-Forwarded-Proto http if !{ ssl_fc }
   http-request redirect scheme https unless { ssl_fc }
   server server1 IP:8888 check ssl ca-file root.pem verify required
   
   
![CleanShot 2023-08-28 at 11 07 02](https://github.com/warp-tech/warpgate/assets/86528548/eae4d004-69cb-448e-86ad-542837978df8)

**Comment by Eugeny** [comment]
WG doesn't support incoming X-Forwarded-For yet but I've converted your ticket to a feature request :)
