### ISSUE TITLE
Does Warpgate support arm64

### ISSUE THREAD

**Issue by nguyenrom** [warp-tech/warpgate#883]
Dear Warpgate,

I have tried with code below but docker return "docker: no matching manifest for linux/arm64/v8 in the manifest list entries."
```
docker run --rm -it -v /home/docker/warpgate/data:/data ghcr.io/warp-tech/warpgate:main setup
```

Thank you,
Nguyen

**Comment by nguyenrom** [comment]
Hi @Eugeny ,

> I think something might be off with the way i'm tagging the images, does `docker run --rm -it ghcr.io/warp-tech/warpgate:main@sha256:f784a933ae00ef34fef99c95bc57ad556b0e2c57fae86754c94e5f7c8e1d1395` work?

this link is not working, error returned:

**Comment by han4wluc** [comment]
this worked for me:

```
docker pull ghcr.io/warp-tech/warpgate:v0.12.0
```
