### ISSUE TITLE
SSH with SSO OOB URL

### ISSUE THREAD

**Issue by BornTKill** [warp-tech/warpgate#907]
Hello,

Congrats for this project. I love it !
I have enable SSO for SSH and the URL to log in is wrong. I mean the port is specify 

Warpgate authentication: please open the following URL in your browser:
https://warpgate.domain.com:**8888**/@warpgate#/login/xxxxxx

My warpgate is is accessible through stand https.
Thank you for you help.

**Comment by lanrat** [comment]
I think this is the same issue as #885 and a fix in #886.
