### ISSUE TITLE
Add arm64 platform in Releases

### ISSUE THREAD

**Issue by sbourdette** [warp-tech/warpgate#91]
Could you add arm64 build in the release through a github action.
It's very difficult to build on ARM with poor performances

Regards

**Comment by filipton** [comment]
I built [container](https://hub.docker.com/r/filipton/warpgate) for arm64, and its working well!
Developers may use buildx for building multi-arch releases.

**Comment by Eugeny** [comment]
Could you check if the built aarch64 binary on the bottom of this page works? https://github.com/warp-tech/warpgate/actions/runs/2929820451

**Comment by Eugeny** [comment]
v0.6 release will include ARM64 builds
