### ISSUE TITLE
LOG Coloration

### ISSUE THREAD

**Issue by BornTKill** [warp-tech/warpgate#919]
Dear,

I am using filebeat to collect docker stdout logs. I would like to disable coloration.
Can you help me ?

`   "message": "\u001b[2m11:03:34\u001b[0m \u001b[32m INFO\u001b[0m \u001b[1mHTTP\u001b[0m: Request \u001b[3mmethod\u001b[0m\u001b[2m=\u001b[0mGET \u001b[3murl\u001b[0m\u001b[2m=\u001b[0m/@warpgate/api/targets?search= \u001b[3mstatus\u001b[0m\u001b[2m=\u001b[0m200 OK `

**Comment by Eugeny** [comment]
Logs are only colored if `stdout` is a TTY - you could pipe `warpgate` through `cat` or run it without `-t` if it's on Docker.
