### ISSUE TITLE
Feat: add expiry option to tickets

### ISSUE THREAD

**Issue by Emiliaaah** [warp-tech/warpgate#924]
It would be awesome if I could give someone a token with which they can log in for a certain period of time. So only give someone the option to use the ticket for the next 30 minutes. Something that would kind of go along side this would be single use tickets.

**Comment by vvrein** [comment]
And the "oneshot" tickets would be nice feature.

**Comment by kakawait** [comment]
I've checked the code, and seems that both feature expiration and number of usage already part of model of the ticket.
Maybe is just missing UI?

**Comment by Eugeny** [comment]
Yes - it was already implemented, just not available to configure through the UI yet

**Comment by kakawait** [comment]
I'll try to contribute on that. But don't block yourself to do it if you want because I'm totally new in rust and svelte so can take some time
