### ISSUE TITLE
API for create and configure host or another way to add entries en masse

### ISSUE THREAD

**Issue by przemekjagielski** [warp-tech/warpgate#926]
Hello, 

My case is easy - i need method for add entries en masse - API Rest, python or bash client or other way. Can you tell me, how can i add a lot of servers to warpgate at this moment, or when could you add this option? Via gui is not for me - i need use of them on ansible.

**Comment by Eugeny** [comment]
You can reuse the admin REST API that the Web UI Itself uses: https://github.com/warp-tech/warpgate/blob/main/warpgate-web/src/admin/lib/openapi-schema.json

To authenticate, issue yourself a ticket for the `warpgate:admin` target and use it with your API requests

**Comment by UMB8998** [comment]
I'm trying to issue a ticket for warpgate:admin but I don't see that target, I tried creating an http target, redirecting to the warpgate instance, but it doesn't work
