### ISSUE TITLE
Cannot use user with scp or rsync

### ISSUE THREAD

**Issue by Rahe** [warp-tech/warpgate#927]
Hello,

When using SCP or Rsync, since the username is having a ":" into it, this is triggering the following error :
```
scp -P someport ./somefile  'njuen:someproject@bastionhost':/srv/somefile.yml
ssh: Could not resolve hostname njuen: nodename nor servname provided, or not known
scp: Connection closed
```

The only solution I have found is to edit my config ssh file and create a custom host for every project I need to send files with scp or rsync.

Is there a workaround ?

Nicolas,

**Comment by vvrein** [comment]
Worked for me:
```
scp -P 2222 -o ControlMaster=no -o User=main:tokk ./httplistener.py 127.0.0.1:/home/vrein/file.py
main:tokk@127.0.0.1's password:
httplistener.py                                                                                                                                                                    100% 1628   222.6KB/s   00:00
```
Just ignore the `-o ControlMaster=no`  part, it was needed due to my local ssh configuration.

**Comment by jeslinmx** [comment]
Should this be added to documentation?

Alternatively, is it possible to switch the user:target separator to some other character that doesn't cause conflicts with `scp`?
