### ISSUE TITLE
Does it support SAML SSO authentication?

### ISSUE THREAD

**Issue by habin201291** [warp-tech/warpgate#928]
I'm having my own simple Saml Identity Provider. May i configure SSO on it?

**Comment by NotSqrt** [comment]
SAML (not OAuth2) would be nice !

**Comment by afterclassroom** [comment]
> So how can i configure it?

here it is https://github.com/warp-tech/warpgate/wiki/SSO-Authentication

**Comment by habin201291** [comment]
> > So how can i configure it?
> 
> here it is https://github.com/warp-tech/warpgate/wiki/SSO-Authentication

This is only for OIDC providers.

**Comment by afterclassroom** [comment]
> SAML (not OAuth2) would be nice !

Do you have documentation using SAML for Warpgate?

**Comment by Eugeny** [comment]
Warpgate doesn't support SAML yet, only OIDC.
