### ISSUE TITLE
How does Warpgate get the email from SSO Reponse

### ISSUE THREAD

**Issue by habin201291** [warp-tech/warpgate#932]
hello,

i'm using [doorkeeper-openid_connect](https://github.com/doorkeeper-gem/doorkeeper-openid_connect) gem as the custom OIDC Provider. When I click the login button with the Custom OIDC provider, I received an error from Warpgate: No e-mail information in the SSO response

I didn't know how Warpgate gets email from SSO response.

Hope this help!

**Comment by Eugeny** [comment]
Warpgate uses the `email` OIDC claim from the response. If the `email_verified` claim is provided then it also must be `true`.

**Comment by habin201291** [comment]
> Warpgate uses the `email` OIDC claim from the response. If the `email_verified` claim is provided then it also must be `true`.

I have resolved it. It turns out that my OIDC provider is not returning the email in the claim.

Thank you for your help!
