### ISSUE TITLE
Erreur 400 : redirect_uri_mismatch / since 0.9.x

### ISSUE THREAD

**Issue by herewithme** [warp-tech/warpgate#941]
Hello,

Thank you for this open-source project.

We have a problem since version 0.9.0 and 0.9.1
SSO authentication has a Google error: redirect_uri_mismatch

We didn't have this problem before the 0.8.x branch.

Any ideas?

**Comment by herewithme** [comment]
We don't have this problem with version 0.8.1.

**Comment by herewithme** [comment]
In version 0.8.1, the Google link is :
https://accounts.google.com/o/oauth2/v2/auth?response_type=code&client_id=XXX.apps.googleusercontent.com&state=XXX&code_challenge=XXX&code_challenge_method=S256&redirect_uri=https://mybastion.url/@warpgate/api/sso/return&scope=openid+email&nonce=XXX

In version 0.9.x, the link is changed to :
https://accounts.google.com/o/oauth2/v2/auth?response_type=code&client_id=XXX.apps.googleusercontent.com&state=XXX&code_challenge=XXX&code_challenge_method=S256&redirect_uri=https://mybastion.url:66718/@warpgate/api/sso/return&scope=openid+email&nonce=XXX

The particularity is that we have a port in the URL of the warpgate web interface, which disappeared with the latest update!

Bug or feature?

**Comment by Eugeny** [comment]
If you have a proxy in front of Warpgate that sets `X-Forwarded-*` headers, set `http.trust_x_forwarded_for` to `true` in the config file.

**Comment by herewithme** [comment]
@Eugeny thanks for your reply

We don't use a reverse proxy, we make a direct call to warpgate.

I try to add this conf value 
```
http:
  enable: true
  trust_x_forwarded_for: true
  listen: "0.0.0.0:66718"
```

It doesn't work any better.

**Comment by herewithme** [comment]
Thanks @Eugeny !
