### ISSUE TITLE
Can set a nginx router use Warpgate-behind-a-reverse-proxy?

### ISSUE THREAD

**Issue by CraKeyBoy** [warp-tech/warpgate#942]
Can I set a nginx  router for warpgate ？

Like this:
server {
    server_name warpgate.acme.inc;
    listen *:443 http2 ssl;
    ssl_certificate ...;
    ssl_certificate_key ...;

    location /wp  {
                proxy_pass https://192.168.10.1:8888/;
                proxy_set_header Host $http_host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_http_version 1.1;
    }
}

**Comment by Eugeny** [comment]
No, warfare can't work behind a URL subpath.
