### ISSUE TITLE
Client IP in logs to ban

### ISSUE THREAD

**Issue by jvinolas** [warp-tech/warpgate#944]
Could it be possible to add the `client_ip` in journald logs so it can be used for example with fail2ban to ban web access attempts? I think should be added in the `log_request_result` function.

**Comment by NefixEstrada** [comment]
Hello,

#945 is ready and working, and solves this issue

**Comment by jvinolas** [comment]
With the #945 that my friend @NefixEstrada did we are already using it in production. This is the `warpgate.conf` filter we use in `fail2ban`:

```
[Definition]
failregex = ^.* warpgate\[\d+\]: .* HTTP: .* method=(\w+) url=([^ ]+) status=401 Unauthorized client_ip=<HOST>
ignoreregex =
```
