### ISSUE TITLE
Option to enable insecure SSH algos per-target - not working

### ISSUE THREAD

**Issue by greg1985** [warp-tech/warpgate#983]
`OpenSSH_8.2p1 Ubuntu-4ubuntu0.4, OpenSSL 1.1.1f  31 Mar 2020
debug1: Reading configuration data /home/maciek/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Connecting to 172.17.61.232 [172.17.61.232] port 22.
debug1: Connection established.
debug1: identity file /home/maciek/.ssh/id_rsa type 0
debug1: identity file /home/maciek/.ssh/id_rsa-cert type -1
debug1: identity file /home/maciek/.ssh/id_dsa type -1
debug1: identity file /home/maciek/.ssh/id_dsa-cert type -1
debug1: identity file /home/maciek/.ssh/id_ecdsa type -1
debug1: identity file /home/maciek/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/maciek/.ssh/id_ecdsa_sk type -1
debug1: identity file /home/maciek/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /home/maciek/.ssh/id_ed25519 type -1
debug1: identity file /home/maciek/.ssh/id_ed25519-cert type -1
debug1: identity file /home/maciek/.ssh/id_ed25519_sk type -1
debug1: identity file /home/maciek/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /home/maciek/.ssh/id_xmss type -1
debug1: identity file /home/maciek/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.4
debug1: Remote protocol version 2.0, remote software version OpenSSH_3.8p1
debug1: match: OpenSSH_3.8p1 pat OpenSSH_3.* compat 0x01000002
debug1: Authenticating to 172.17.61.232:22 as 'admin'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: (no match)
Unable to negotiate with 172.17.61.232 port 22: no matching key exchange method found. Their offer: diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1`

_Originally posted by @greg1985 in https://github.com/warp-tech/warpgate/issues/961#issuecomment-1978606805_

**Comment by budachst** [comment]
I tried out yesterday's nightly build of Wargate, which actually keeps the switch to allow for insecure algos at the target after updating the configuration. However, Warpgate still refuses connections to our old Sun servers, which only offer ssh-rsa and ssh-dss:

Connection error error: Ssh(NoCommonAlgo { kind: Key, ours: ["ssh-ed25519", "ecdsa-sha2-nistp256", "ecdsa-sha2-nistp521", "rsa-sha2-256", "rsa-sha2-512"], theirs: ["ssh-rsa", "ssh-dss"] })

**Comment by Eugeny** [comment]
The new nightly should be available in a bit!
