### ISSUE TITLE
log file transfers over scp

### ISSUE THREAD

**Issue by Vinicius-valenca** [warp-tech/warpgate#985]
https://github.com/warp-tech/warpgate/issues/984
related issue. 
i already have the vector working, but on the log this is only what i can see, i want to get que log on files operations as well, this is possible ?
i know that when we use the warpgate in debug mode i can see this on the terminal.

Thanks

`

Time | MessageLive -- | -- 29/04/2024, 15:04:43 | Connectedaddress:10.0.2.15:22 29/04/2024, 15:04:43 | Connectingaddress:10.0.2.15:22username:vinicius 29/04/2024, 15:04:43 | Requesting subsystem sftpchannel:f757b832-5c22-43d1-85d6-85b89da93761client_ip:10.1.0.130 29/04/2024, 15:04:43 | Opening session channelchannel:f757b832-5c22-43d1-85d6-85b89da93761client_ip:10.1.0.130 29/04/2024, 15:04:43 | Authenticatedclient_ip:10.1.0.130credentials:public keyusername:vinicius 29/04/2024, 15:04:43 | Public key auth as with key xxxxx =client_ip:10.1.0.130   | End of the log `

**Comment by Eugeny** [comment]
It's not possible for Warpgate to log individual transfers since subsystem channels (like SFTP) are completely opaque to it.
