### ISSUE TITLE
Can't SSH into a VM

### ISSUE THREAD

**Issue by jsJack** [warp-tech/warpgate#986]
Hey,

Been having a weird issue lately - re-imaged one of my VMs (so it's SSH host key would have changed), and now I get this issue when trying to connect. Doesn't happen for any other host.

I'm running Warpgate on Docker.

![image](https://github.com/warp-tech/warpgate/assets/55438332/e443e694-f792-40ee-9690-eda9b9e0883e)

**Comment by Eugeny** [comment]
Can you check the debug log on the server side? If you don't see anything interesting, run Warpgate with `--debug`

**Comment by jsJack** [comment]
@Eugeny Where is the debug log stored on the server side if in a container?

**Comment by Eugeny** [comment]
It's just directly logging to the container's stdout

**Comment by jsJack** [comment]
```
warpgate-1  | 11:49:08  WARN Host key is invalid! session=1b04fc7e-0e19-4326-8142-39d53372beb8
warpgate-1  | 11:49:08 ERROR SSH: Connection error error=HostKeyMismatch { received_key_type: "ssh-ed25519", received_key_base64: "AAAAC3NzaC1lZDI1NTE5AAAAILdjWoJBsh3aeMFDnD1Z4nDwAKe06x82Yv9Ox2Gw1ivK", known_key_type: "ssh-ed25519", known_key_base64: "AAAAC3NzaC1lZDI1NTE5AAAAIEksRfAJp0ZKmrPYaNOvF1wAt+2LyNlDdt0X8V0NOnEa" } session=1b04fc7e-0e19-4326-8142-39d53372beb8
```

Pretty much what I'd guessed had been the case - but how would I reset the host key? It's a Dev VM so I'll be reimaging it about 70 times a day 😂

**Comment by Eugeny** [comment]
You'd need to remove it from the known hosts in the Warpgate UI or use the Warpgate's API to remove the key automatically. Also subscribe to #918 - I'll try to add this as an UI option soon.

**Comment by jsJack** [comment]
Ahhhh that makes total sense now. Completely missed the SSH tab in the Admin UI.
Help is much appreciated, thanks for the quick reply!
